env:

  - IMAGE=linux-x64 PY_VERSION=3.8.5
  - IMAGE=linux-x64 PY_VERSION=3.8.4
  - IMAGE=linux-x64 PY_VERSION=3.8.3
  - IMAGE=linux-x64 PY_VERSION=3.8.2
  - IMAGE=linux-x64 PY_VERSION=3.8.1
  - IMAGE=linux-x64 PY_VERSION=3.8.0
  - IMAGE=linux-x64 PY_VERSION=3.7.7
  - IMAGE=linux-x64 PY_VERSION=3.7.6
  - IMAGE=linux-x64 PY_VERSION=3.6.9
  - IMAGE=linux-x64 PY_VERSION=3.5.9
  - IMAGE=linux-x64 PY_VERSION=2.7.17

  - IMAGE=linux-x86 PY_VERSION=3.8.5
  - IMAGE=linux-x86 PY_VERSION=3.8.4
  - IMAGE=linux-x86 PY_VERSION=3.8.3
  - IMAGE=linux-x86 PY_VERSION=3.8.2
  - IMAGE=linux-x86 PY_VERSION=3.8.1
  - IMAGE=linux-x64 PY_VERSION=3.8.0
  - IMAGE=linux-x86 PY_VERSION=3.7.7
  - IMAGE=linux-x64 PY_VERSION=3.7.6
  - IMAGE=linux-x86 PY_VERSION=3.6.9
  - IMAGE=linux-x86 PY_VERSION=3.5.9
  - IMAGE=linux-x86 PY_VERSION=2.7.17
command:
  - |
    if [[ $STEP == "dependencies" ]]; then
      ci_addons docker load-pull-save dockcross/$IMAGE
      docker run dockcross/$IMAGE > ~/bin/dockcross-$IMAGE; chmod u+x ~/bin/dockcross-$IMAGE
    fi
  - |
    if [[ $STEP == "test" ]]; then
      DOCKER_ARGS="-e PY_VERSION=$PY_VERSION -e CIRCLE_SHA1 -e CIRCLE_PR_NUMBER -e CIRCLE_BRANCH -v $HOME/scripts:/usr/scripts"
      dockcross-$IMAGE  -a "$DOCKER_ARGS" ctest -S /usr/scripts/circle_dashboard.cmake -VV
    fi
