os:
  - linux
  - osx

language: c

compiler:
 - gcc
 - clang

env:
 - PY_VERSION=3.8.5
 - PY_VERSION=3.8.4
 - PY_VERSION=3.8.3
 - PY_VERSION=3.8.2
 - PY_VERSION=3.8.1
 - PY_VERSION=3.8.0
 - PY_VERSION=3.7.7
 - PY_VERSION=3.7.6
 - PY_VERSION=3.7.5
 - PY_VERSION=3.7.4
 - PY_VERSION=3.7.4
 - PY_VERSION=3.7.3
 - PY_VERSION=3.7.2
 - PY_VERSION=3.7.1
   # - PY_VERSION=3.7.0

 - PY_VERSION=3.6.10
 - PY_VERSION=3.6.9
 - PY_VERSION=3.6.8
 - PY_VERSION=3.6.7
 - PY_VERSION=3.6.6
 - PY_VERSION=3.6.5
 - PY_VERSION=3.6.4
 - PY_VERSION=3.6.3
 - PY_VERSION=3.6.2
 - PY_VERSION=3.6.1
 - PY_VERSION=3.6.0

 - PY_VERSION=3.5.9
 - PY_VERSION=3.5.8
 - PY_VERSION=3.5.7
 - PY_VERSION=3.5.6
 - PY_VERSION=3.5.5
 - PY_VERSION=3.5.4
 - PY_VERSION=3.5.3
 - PY_VERSION=3.5.2
 - PY_VERSION=3.5.1

 - PY_VERSION=2.7.17
 - PY_VERSION=2.7.16
 - PY_VERSION=2.7.15
 - PY_VERSION=2.7.14
 - PY_VERSION=2.7.13
 - PY_VERSION=2.7.12
 - PY_VERSION=2.7.11
 - PY_VERSION=2.7.10
 - PY_VERSION=2.7.9
 - PY_VERSION=2.7.8
 - PY_VERSION=2.7.7
 - PY_VERSION=2.7.6
 - PY_VERSION=2.7.5
 - PY_VERSION=2.7.4
 - PY_VERSION=2.7.3

sudo: false

branches:
 only:
  - /^ci.*$/

addons:
  apt:
    packages:
     - libssl-dev

before_script:
 - wget -P /tmp/ https://raw.githubusercontent.com/davidsansome/python-cmake-buildsystem/dashboard/travis_dashboard.cmake

script:
 - ctest -V -S /tmp/travis_dashboard.cmake

after_script:
 - cat ${TRAVIS_BUILD_DIR}-build/CMakeCache.txt

