os:
  - linux

language: c

compiler:
 - gcc

env:
 global:
  - secure: "fjp3C/ftKPLF01wClsWXI2wz4pfgSIwiF8VUUOCjMkgLSIPWQROI3yGdZRuG7KBKBng/ssRRJ/IW98v4lRzkbx3WK6wsyubzE5+a3JSyxNB47mS1ZDIspOWhjGAbtUg5sStkE2pwWl87jpIq5HZr2ugKcR5ShSaNcbv/YrUGdD0="

sudo: false

branches:
 only:
  - master
  - /^ci.*$/

addons:
  apt:
    packages:
     - libssl-dev

before_script:
 - wget -P /tmp/ https://raw.githubusercontent.com/davidsansome/python-cmake-buildsystem/dashboard/travis_dashboard.cmake

install:
 - wget https://raw.githubusercontent.com/scikit-build/scikit-ci-addons/master/travis/enable-worker-remote-access.sh -O ../enable-worker-remote-access.sh
 - chmod u+x ../enable-worker-remote-access.sh

script:
 - ctest -V -S /tmp/travis_dashboard.cmake

after_script:
 - cat ${TRAVIS_BUILD_DIR}-build/CMakeCache.txt

after_success:
 - ../enable-worker-remote-access.sh

after_failure:
 - ../enable-worker-remote-access.sh

