version: 1.0.{build}

image: Visual Studio 2015

branches:
 only:
  - /^ci.*$/

platform: Any CPU

configuration: Release

# Default GENERATOR is set to "Visual Studio 9 2008"
# See https://github.com/python-cmake-buildsystem/python-cmake-buildsystem/blob/dashboard/appveyor_dashboard.cmake
environment:
  matrix:

  - PY_VERSION: 3.8.5
    APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
    ARCH: win64
    GENERATOR: "Visual Studio 15 2017 Win64"
  - PY_VERSION: 3.8.5
    APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
    ARCH: win32
    GENERATOR: "Visual Studio 15 2017"

  - PY_VERSION: 3.8.5
    APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
    ARCH: win64
    GENERATOR: "Visual Studio 15 2017 Win64"
  - PY_VERSION: 3.8.5
    APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
    ARCH: win32
    GENERATOR: "Visual Studio 15 2017"

  - PY_VERSION: 3.8.4
    APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
    ARCH: win64
    GENERATOR: "Visual Studio 15 2017 Win64"
  - PY_VERSION: 3.8.4
    APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
    ARCH: win32
    GENERATOR: "Visual Studio 15 2017"

  - PY_VERSION: 3.8.4
    APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
    ARCH: win64
    GENERATOR: "Visual Studio 15 2017 Win64"
  - PY_VERSION: 3.8.4
    APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
    ARCH: win32
    GENERATOR: "Visual Studio 15 2017"

  - PY_VERSION: 3.8.3
    APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
    ARCH: win64
    GENERATOR: "Visual Studio 15 2017 Win64"
  - PY_VERSION: 3.8.3
    APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
    ARCH: win32
    GENERATOR: "Visual Studio 15 2017"

  - PY_VERSION: 3.8.3
    APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
    ARCH: win64
    GENERATOR: "Visual Studio 15 2017 Win64"
  - PY_VERSION: 3.8.3
    APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
    ARCH: win32
    GENERATOR: "Visual Studio 15 2017"

  - PY_VERSION: 3.8.2
    APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
    ARCH: win64
    GENERATOR: "Visual Studio 15 2017 Win64"
  - PY_VERSION: 3.8.2
    APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
    ARCH: win32
    GENERATOR: "Visual Studio 15 2017"

  - PY_VERSION: 3.8.1
    APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
    ARCH: win64
    GENERATOR: "Visual Studio 15 2017 Win64"
  - PY_VERSION: 3.8.1
    APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
    ARCH: win32
    GENERATOR: "Visual Studio 15 2017"

  - PY_VERSION: 3.8.0
    APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
    ARCH: win64
    GENERATOR: "Visual Studio 15 2017 Win64"
  - PY_VERSION: 3.8.0
    APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
    ARCH: win32
    GENERATOR: "Visual Studio 15 2017"

  - PY_VERSION: 3.7.7
    APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
    ARCH: win64
    GENERATOR: "Visual Studio 15 2017 Win64"
  - PY_VERSION: 3.7.7
    APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
    ARCH: win32
    GENERATOR: "Visual Studio 15 2017"

  - PY_VERSION: 3.7.6
    APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
    ARCH: win64
    GENERATOR: "Visual Studio 15 2017 Win64"
  - PY_VERSION: 3.7.6
    APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
    ARCH: win32
    GENERATOR: "Visual Studio 15 2017"

  - PY_VERSION: 3.7.5
    APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
    ARCH: win64
    GENERATOR: "Visual Studio 15 2017 Win64"
  - PY_VERSION: 3.7.5
    APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
    ARCH: win32
    GENERATOR: "Visual Studio 15 2017"

  - PY_VERSION: 3.7.4
    APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
    ARCH: win64
    GENERATOR: "Visual Studio 15 2017 Win64"
  - PY_VERSION: 3.7.4
    APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
    ARCH: win32
    GENERATOR: "Visual Studio 15 2017"

  - PY_VERSION: 3.7.3
    APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
    ARCH: win64
    GENERATOR: "Visual Studio 15 2017 Win64"
  - PY_VERSION: 3.7.3
    APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
    ARCH: win32
    GENERATOR: "Visual Studio 15 2017"

  - PY_VERSION: 3.7.2
    APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
    ARCH: win64
    GENERATOR: "Visual Studio 15 2017 Win64"
  - PY_VERSION: 3.7.2
    APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
    ARCH: win32
    GENERATOR: "Visual Studio 15 2017"

  - PY_VERSION: 3.7.1
    APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
    ARCH: win64
    GENERATOR: "Visual Studio 15 2017 Win64"
  - PY_VERSION: 3.7.1
    APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
    ARCH: win32
    GENERATOR: "Visual Studio 15 2017"

  - PY_VERSION: 3.7.0
    APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
    ARCH: win64
    GENERATOR: "Visual Studio 15 2017 Win64"
  - PY_VERSION: 3.7.0
    APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
    ARCH: win32
    GENERATOR: "Visual Studio 15 2017"

  - PY_VERSION: 3.6.10
    APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015
    ARCH: win64
    GENERATOR: "Visual Studio 14 2015 Win64"
  - PY_VERSION: 3.6.10
    APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015
    ARCH: win32
    GENERATOR: "Visual Studio 14 2015"

  - PY_VERSION: 3.6.9
    APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015
    ARCH: win64
    GENERATOR: "Visual Studio 14 2015 Win64"
  - PY_VERSION: 3.6.9
    APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015
    ARCH: win32
    GENERATOR: "Visual Studio 14 2015"

  - PY_VERSION: 3.6.8
    APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015
    ARCH: win64
    GENERATOR: "Visual Studio 14 2015 Win64"
  - PY_VERSION: 3.6.8
    APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015
    ARCH: win32
    GENERATOR: "Visual Studio 14 2015"

  - PY_VERSION: 3.6.6
    APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015
    ARCH: win64
    GENERATOR: "Visual Studio 14 2015 Win64"
  - PY_VERSION: 3.6.6
    APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015
    ARCH: win32
    GENERATOR: "Visual Studio 14 2015"

  - PY_VERSION: 3.6.5
    APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015
    ARCH: win64
    GENERATOR: "Visual Studio 14 2015 Win64"
  - PY_VERSION: 3.6.5
    APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015
    ARCH: win32
    GENERATOR: "Visual Studio 14 2015"

  - PY_VERSION: 3.6.4
    APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015
    ARCH: win64
    GENERATOR: "Visual Studio 14 2015 Win64"
  - PY_VERSION: 3.6.4
    APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015
    ARCH: win32
    GENERATOR: "Visual Studio 14 2015"

  - PY_VERSION: 3.6.3
    APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015
    ARCH: win64
    GENERATOR: "Visual Studio 14 2015 Win64"
  - PY_VERSION: 3.6.3
    APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015
    ARCH: win32
    GENERATOR: "Visual Studio 14 2015"

  - PY_VERSION: 3.6.2
    APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015
    ARCH: win64
    GENERATOR: "Visual Studio 14 2015 Win64"
  - PY_VERSION: 3.6.2
    APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015
    ARCH: win32
    GENERATOR: "Visual Studio 14 2015"

  - PY_VERSION: 3.6.1
    APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015
    ARCH: win64
    GENERATOR: "Visual Studio 14 2015 Win64"
  - PY_VERSION: 3.6.1
    APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015
    ARCH: win32
    GENERATOR: "Visual Studio 14 2015"

  - PY_VERSION: 3.6.0
    APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015
    ARCH: win64
    GENERATOR: "Visual Studio 14 2015 Win64"
  - PY_VERSION: 3.6.0
    APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015
    ARCH: win32
    GENERATOR: "Visual Studio 14 2015"

  - PY_VERSION: 3.5.9
    APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015
    ARCH: win64
    GENERATOR: "Visual Studio 14 2015 Win64"
  - PY_VERSION: 3.5.9
    APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015
    ARCH: win32
    GENERATOR: "Visual Studio 14 2015"

  - PY_VERSION: 3.5.8
    APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015
    ARCH: win64
    GENERATOR: "Visual Studio 14 2015 Win64"
  - PY_VERSION: 3.5.8
    APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015
    ARCH: win32
    GENERATOR: "Visual Studio 14 2015"

  - PY_VERSION: 3.5.7
    APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015
    ARCH: win64
    GENERATOR: "Visual Studio 14 2015 Win64"
  - PY_VERSION: 3.5.7
    APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015
    ARCH: win32
    GENERATOR: "Visual Studio 14 2015"

  - PY_VERSION: 3.5.6
    APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015
    ARCH: win64
    GENERATOR: "Visual Studio 14 2015 Win64"
  - PY_VERSION: 3.5.6
    APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015
    ARCH: win32
    GENERATOR: "Visual Studio 14 2015"

  - PY_VERSION: 3.5.5
    APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015
    ARCH: win64
    GENERATOR: "Visual Studio 14 2015 Win64"
  - PY_VERSION: 3.5.5
    APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015
    ARCH: win32
    GENERATOR: "Visual Studio 14 2015"

  - PY_VERSION: 3.5.4
    APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015
    ARCH: win64
    GENERATOR: "Visual Studio 14 2015 Win64"
  - PY_VERSION: 3.5.4
    APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015
    ARCH: win32
    GENERATOR: "Visual Studio 14 2015"
   
# Patches not working on windows
# - PY_VERSION: 2.7.17
#   APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015
#   ARCH: win64
#   GENERATOR: "Visual Studio 14 2015 Win64"
# - PY_VERSION: 2.7.17
#   APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015
#   ARCH: win32
#   GENERATOR: "Visual Studio 14 2015"
#  
# - PY_VERSION: 2.7.16
#   APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015
#   ARCH: win64
#   GENERATOR: "Visual Studio 14 2015 Win64"
# - PY_VERSION: 2.7.16
#   APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015
#   ARCH: win32
#   GENERATOR: "Visual Studio 14 2015"
   
  - PY_VERSION: 2.7.15
    APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015
    ARCH: win64
    GENERATOR: "Visual Studio 14 2015 Win64"
  - PY_VERSION: 2.7.15
    APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015
    ARCH: win32
    GENERATOR: "Visual Studio 14 2015"
    
  - PY_VERSION: 2.7.14
    APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015
    ARCH: win64
    GENERATOR: "Visual Studio 14 2015 Win64"
  - PY_VERSION: 2.7.14
    APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015
    ARCH: win32
    GENERATOR: "Visual Studio 14 2015"

  - PY_VERSION: 2.7.14
    APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2013
    ARCH: win64
    GENERATOR: "Visual Studio 12 2013 Win64"
  - PY_VERSION: 2.7.14
    APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2013
    ARCH: win32
    GENERATOR: "Visual Studio 12 2013"

  - PY_VERSION: 2.7.13
    APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2013
    ARCH: win64
    GENERATOR: "Visual Studio 12 2013 Win64"
  - PY_VERSION: 2.7.13
    APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2013
    ARCH: win32
    GENERATOR: "Visual Studio 12 2013"

  - PY_VERSION: 2.7.12
    APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2013
    ARCH: win64
    GENERATOR: "Visual Studio 12 2013 Win64"
  - PY_VERSION: 2.7.12
    APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2013
    ARCH: win32
    GENERATOR: "Visual Studio 12 2013"

  - PY_VERSION: 2.7.11
    APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2013
    ARCH: win64
    GENERATOR: "Visual Studio 12 2013 Win64"
  - PY_VERSION: 2.7.11
    APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2013
    ARCH: win32
    GENERATOR: "Visual Studio 12 2013"

  - PY_VERSION: 2.7.10
    APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2013
    ARCH: win64
    GENERATOR: "Visual Studio 12 2013 Win64"
  - PY_VERSION: 2.7.10
    APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2013
    ARCH: win32
    GENERATOR: "Visual Studio 12 2013"

  - PY_VERSION: 2.7.9
    APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2013
    ARCH: win64
    GENERATOR: "Visual Studio 12 2013 Win64"
  - PY_VERSION: 2.7.9
    APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2013
    ARCH: win32
    GENERATOR: "Visual Studio 12 2013"

  - PY_VERSION: 2.7.8
    APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2013
    ARCH: win64
    GENERATOR: "Visual Studio 12 2013 Win64"
  - PY_VERSION: 2.7.8
    APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2013
    ARCH: win32
    GENERATOR: "Visual Studio 12 2013"

  - PY_VERSION: 2.7.7
    APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2013
    ARCH: win64
    GENERATOR: "Visual Studio 12 2013 Win64"
  - PY_VERSION: 2.7.7
    APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2013
    ARCH: win32
    GENERATOR: "Visual Studio 12 2013"

  - PY_VERSION: 2.7.6
    APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2013
    ARCH: win64
    GENERATOR: "Visual Studio 12 2013 Win64"
  - PY_VERSION: 2.7.6
    APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2013
    ARCH: win32
    GENERATOR: "Visual Studio 12 2013"

  - PY_VERSION: 2.7.5
    APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2013
    ARCH: win64
    GENERATOR: "Visual Studio 12 2013 Win64"
  - PY_VERSION: 2.7.5
    APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2013
    ARCH: win32
    GENERATOR: "Visual Studio 12 2013"

  - PY_VERSION: 2.7.4
    APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2013
    ARCH: win64
    GENERATOR: "Visual Studio 12 2013 Win64"
  - PY_VERSION: 2.7.4
    APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2013
    ARCH: win32
    GENERATOR: "Visual Studio 12 2013"

  - PY_VERSION: 2.7.3
    APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2013
    ARCH: win64
    GENERATOR: "Visual Studio 12 2013 Win64"
  - PY_VERSION: 2.7.3
    APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2013
    ARCH: win32
    GENERATOR: "Visual Studio 12 2013"

install:
  - ps: |
      $scripts_dir="$env:APPVEYOR_BUILD_FOLDER\scripts"
      mkdir $scripts_dir
      $source="https://raw.githubusercontent.com/davidsansome/python-cmake-buildsystem/dashboard/appveyor_dashboard.cmake"
      $destination="$scripts_dir\appveyor_dashboard.cmake"
      (New-Object Net.WebClient).DownloadFile($source, $destination)


build_script:
  - ctest -V -C %configuration% -S "%APPVEYOR_BUILD_FOLDER%\\scripts\\appveyor_dashboard.cmake"

test: off

deploy: off
